import { useTranslation } from "react-i18next";
import BottomModal from "../components/BottomModal";

import SlotCard from "../components/SlotCard";
// import { useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { useVerifyHouseholdAccess } from "../hooks/useHousehold";
import { Lock, ArrowLeft, CheckCircle2, Building } from "lucide-react";
import { ROUTES } from "../routes/routes.constants";
import { useHistory } from "react-router-dom";
import { HouseholdData } from "../lib/databaseTypes";
import AccessCodeInput from "./AccessCodeInput";

interface JoinHouseholdModalProps {
  isOpen: boolean;
  onClose: () => void;
  householdData: HouseholdData | null;
}

export default function JoinHouseholdModal({ isOpen, onClose, householdData }: JoinHouseholdModalProps) {
  const { t } = useTranslation();
  const history = useHistory();
  
  // State Machine parameters
  const [accessCode, setAccessCode] = useState('');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const { mutateAsync: verifyAccess, isPending: isVerifying } = useVerifyHouseholdAccess();

  // Flush states completely on modal exit transitions
  useEffect(() => {
    if (!isOpen) {
      setAccessCode('');
      setErrorMessage(null);
    }
  }, [isOpen]);

  // Step 2 Action handler logic: Validates password code parameter straight to Supabase
  const handleVerifyAccessCode = async () => {
    if (!accessCode.trim()) {
      setErrorMessage("Please enter a code.");
      return;
    }
    if (!householdData?.id) return;

    setErrorMessage(null);

    try {
      // Execute the hook mutation triggers
      const result = await verifyAccess({ 
        householdId: householdData.id, 
        inputCode: accessCode.trim() 
      });

      if (result.success) {
        localStorage.setItem('householdId', householdData.id);
        history.push(ROUTES.APARTMENT_LOGIN);
        onClose();
        
      } else {
        setErrorMessage(t('joinHousehold.error_invalid_code', 'Incorrect access code. Please try again.'));
      }
    } catch (err: unknown) {
      setErrorMessage(`${t('common.system_error', 'Incorrect access code. Please try again.')} (${err instanceof Error ? err.message : String(err)})`);
    }
  };
  if (!isOpen || !householdData) return null;

  return (
    <BottomModal 
      isOpen={isOpen} 
      onClose={onClose} 
      title={ t('joinHousehold.title_verify', 'Enter Access Code')
      }
    >
      <div className="flex flex-col gap-4 mt-4 mb-4 min-h-[280px] transition-all">
                  
          {/* Display static reference of the building selection */}
            <SlotCard title={householdData.address} subtitle={householdData.name} icon={<Building className="w-5 h-5" />} />

          <span className="text-sm text-gray-400">
            {t('joinHousehold.instruction_code', 'Please enter the access code generated by your property manager to unlock this workspace context.')}
          </span>
          {/* Structured custom input field frame */}
          <div className="flex flex-col gap-4 mt-4">
            <div className="flex flex-row gap-2 items-center">
              <Lock className="w-4 h-4 text-gray-400" />
              <label className="text-xs font-bold text-gray-400 uppercase tracking-wider px-1">
                {t('joinHousehold.label_code', 'Security Code')}
              </label>
            </div>
            <div className="relative w-full">
              <AccessCodeInput 
                accessCode={accessCode}
                disabled={isVerifying}
                setAccessCode={setAccessCode}
              />
            </div>
          </div>

          {/* Real-time inline validation error feedback banner */}
          {errorMessage && (
            <div className="p-3 rounded-xl bg-red-50 dark:bg-red-950/20 border border-red-100 dark:border-red-900 text-xs font-semibold text-red-600 dark:text-red-400 text-center animate-shake">
              {errorMessage}
            </div>
          )}

          {/* Direct operation action triggers */}
          <div className="flex flex-col gap-2 mt-2">
            <button
              type="button"
              onClick={handleVerifyAccessCode}
              disabled={isVerifying}
              className="w-full py-3.5 bg-blue-600 hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-500 text-white font-bold rounded-xl transition-all flex items-center justify-center gap-2 text-sm shadow-sm active:scale-[0.99] disabled:opacity-50"
            >
              {isVerifying ? (
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <>
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{t('joinHousehold.btn_verify', 'Verify & Connect')}</span>
                </>
              )}
            </button>

            <button
              type="button"
              onClick={() => {
                setAccessCode('');
                setErrorMessage(null);
                onClose();
              }}
              disabled={isVerifying}
              className="w-full py-3 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 font-semibold transition-colors flex items-center justify-center gap-1.5 text-xs disabled:opacity-50"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>{t('joinHousehold.btn_back', 'Back to Search')}</span>
            </button>
          </div>
        </div>
        

    </BottomModal>
  );
}
